# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - docker build . -f Dockerfile.ros.foxy -t codustry/ros:foxy-ros-base-l4t-r32.5.0
  push:
    cmds:
      - docker push codustry/ros:foxy-ros-base-l4t-r32.5.0
